@extends('layouts.app')

@section('content')
          <article class="msc-block msc-slider">
            <h1 class="msc-block__title">
              Terms of Service
            </h1>
            <div class="msc-block-info">
<p><strong>ACCEPTABLE USE POLICY</strong></p>
<p>Terms of service also includes our Acceptable Use Policy.</p>
<br/>
<p><strong>ENFORCEMENT</strong></p>
<p>Mage Security Council may investigate any reported or suspected violation of this Agreement or of the Acceptable Use Policy and take any action that it deems appropriate and reasonable under the circumstance to protect its systems, facilities, customers and/or third parties. Mage Security Council will not access or review the contents of any e-mail or similar stored electronic communications except as required or permitted by applicable law or legal process.</p>
<p>Mage Security Council reserves the right to refuse or discontinue service to anyone at Mage Security Council's sole discretion. Mage Security Council may deny you access to all or part of the service without notice if you engage in any conduct or activities that Mage Security Council, in its sole discretion, believes violates any of the terms and conditions in this Agreement or of the Acceptable Use Policy. Mage Security Council shall have no responsibility to notify any third-party providers of services, merchandise, or information, nor any responsibility for any consequences resulting from such discontinuance or lack of notification. You agree that Mage Security Council has the right to monitor the service electronically from time to time and to disclose any information as necessary to satisfy the law, or to protect itself or its subscribers. Mage Security Council also reserves the right to refuse refunds in cases where Mage Security Council believes abuse has taken place.</p>
<br/>
<p><strong>PUBLIC NATURE OF THE INTERNET</strong></p>
<p>Please understand that all information submitted on your hosting account shall be considered publicly accessible. Important and private information should be protected/backed up by you. For example, we are not liable for protection or privacy of electronic mail or other information transferred through the Internet or any other network provider that you may use.</p>
<br/>
<p><strong>NO SERVICE WARRANTIES</strong></p>
<p>Mage Security Council makes no warranties or representations of any kind for the services being offered. The Service is provided on an "as-is" and "as-available" basis without warranties of any kind, either express or implied, including but not limited to warranties of title, non-infringement, or implied warranties of merchantability or fitness for a particular purpose. No advice or information given by Mage Security Council or its agents or employees shall create a warranty. Mage Security Council provides no warranty that the service will be uninterrupted or error free unless otherwise stated in our Service Level Agreement (SLA), or that any information, software or other material accessible on the service is free from viruses or other harmful components. Under no circumstances shall Mage Security Council be liable for any direct, indirect, special, punitive, or consequential damages that result in any way from your use of or inability to use the service, or for third parties' use of the service to access your Web space, or to access the Internet or any part thereof, or your or any third parties' reliance on or use of information, services, or merchandise provided on or through the service, or that result from mistakes, omissions, interruptions, deletion of files, errors, defects, delays in operation or transmission, or any failure of performance. If you are dissatisfied with Mage Security Council's service or any of its terms, conditions, rules, policies, guidelines, or practices, your sole and exclusive remedy is to discontinue using the service.</p>
<br/>
<p><strong>INTELLECTUAL PROPERTY RIGHTS</strong></p>
<p>Your License Grant to Mage Security Council. You hereby grant to Mage Security Council a non-exclusive, worldwide, and royalty-free license for the Initial Term and any Renewal Term to use your content as necessary for the purposes of rendering and operating the Services to you under this Agreement. You expressly (a) grant to Mage Security Council a license to cache materials distributed or made available for distribution via the Services, including content supplied by third parties, and (b) agree that such caching is not an infringement of any of your intellectual property rights or any third party's intellectual property rights.</p>
<p>Mage Security Council Materials and Intellectual Property. All materials, including but not limited to any computer software (in object code and source code form), data or information developed or provided by Mage Security Council or its suppliers or agents pursuant to this Agreement, and any know-how, methodologies, equipment, or processes used by Mage Security Council to provide the Services to you, including, without limitation, all copyrights, trademarks, patents, trade secrets and other proprietary rights are and will remain the sole and exclusive property of Mage Security Council or its suppliers, including but not limited to any software programs, inventions, products and/or technology innovations and methodologies utilized, developed, or disclosed by Mage Security Council during the term of this Agreement. Unauthorized copying, reverse engineering, decompiling, and creating derivative works based on the any such software is expressly forbidden except as permitted in this Agreement. You may be held legally responsible for violation of any patent rights, copyright or trade secret rights that is caused or encouraged by failure to abide by the terms of this Agreement.</p>
<p>You hereby grant to Mage Security Council a limited right to use your trademarks, if any, for the limited purpose of permitting Mage Security Council to fulfill its duties under this Agreement. This is not a trademark license, and no other rights relating to the trademarks are granted by this Agreement. Specifically, but without limitation, the rights granted by this Agreement do not include the right to sublicense use of your trademarks or to use your trademarks with any other products or services outside the scope of the Services provided under this Agreement. The limited trademark use rights granted under this section terminate upon termination of this Agreement.</p>
<br/>
<p><strong>INDEMNIFICATION AND EXCLUSION OF LIABILITY</strong></p>
<p>You agree to indemnify, defend, and hold harmless Mage Security Council from any and all liability, penalties, losses, damages, costs, expenses, attorneys' fees, causes of action or claims caused by or resulting indirectly from your use of the service which damages either you, Mage Security Council, or any other party or parties without limitation or exception. This indemnification and hold harmless agreement extends to all issues associated with your account, including but not limited to domain name selection and website content.</p>
<p>You hereby acknowledge and agree that Mage Security Council will not be liable for any temporary delays, outages or interruptions of the Services unless such outage or delay is covered by our Service Level Agreement. Further, Mage Security Council shall not be liable for any delay or failure to perform its obligations under this Agreement, where such delay or failure results from any act of God or other cause beyond its reasonable control (including, without limitation, any mechanical, electronic, communications or third-party supplier failure).</p>
<br/>
<p><strong>MISCELLANEOUS</strong></p>
<p>In the event that any portion of this Agreement is held to be unenforceable, the unenforceable portion shall be construed in accordance with applicable law as nearly as possible to reflect the original intentions of the parties and the remainder of the provisions shall remain in full force and effect.</p>
<p>Mage Security Council's failure to insist upon or enforce strict performance of any provision of this Agreement shall not be construed as a waiver of any provision or right. Neither the course of conduct between parties nor trade practice shall act to modify any provision of this Agreement.</p>
<p>Mage Security Council may modify this Agreement from time to time, your continued use of the Service shall be deemed to be your acceptance. If you do not agree to this Agreement, you must immediately stop using the Service.</p>
<p>This Agreement shall be governed by and construed in accordance with the laws of the State of Michigan, without regard to its conflicts of law provisions. Any cause of action you may have with respect to the Service must be commenced within one (1) year after the claim or cause of action arises or such claim or cause of action is barred.</p>
<p>Mage Security Council reserves the right to change or modify any of the terms and conditions contained in this Agreement, any Addendums and any policy or guideline incorporated by reference at any time and from time to time in its sole discretion, and to determine whether and when any such changes apply to both existing or future customers. Any changes or modification will be effective upon posting of the revisions on the Mage Security Council Website (the "Site"). Mage Security Council may post changes or modifications to this document, the referenced Acceptable Use Policies and Service Level Agreement without notice to you. Your continued use of Services following Mage Security Council's posting of any changes or modifications will constitute your acceptance of such changes or modifications.</p>

            </div>
          </article>
@endsection